export const EVENTOS = {
  pista: [
    { id: "30-ent", nombre: "30 m", viento: true },
    { id: "50-ent", nombre: "50 m", viento: true },
    { id: "60", nombre: "60 m", viento: true },
    { id: "70", nombre: "70 m", viento: true },
    { id: "80-ent", nombre: "80 m", viento: true },
    { id: "90", nombre: "90 m", viento: true },
    { id: "100", nombre: "100 m", viento: true },
    { id: "120-ent", nombre: "120 m", viento: true },
    { id: "150-ent", nombre: "150 m", viento: true },
    { id: "200", nombre: "200 m", viento: true },
    { id: "250", nombre: "250 m", viento: false },
    { id: "300-ent", nombre: "300 m", viento: false },
    { id: "400", nombre: "400 m", viento: false },
    { id: "600-ent", nombre: "600 m", viento: false },
    { id: "800", nombre: "800 m", viento: false },
    { id: "1000", nombre: "1000 m", viento: false },
    { id: "1500", nombre: "1500 m", viento: false },
    { id: "milla", nombre: "Milla", viento: false },
    { id: "3000", nombre: "3000 m", viento: false },
    { id: "5000", nombre: "5000 m", viento: false },
    { id: "10000", nombre: "10000 m", viento: false },
    { id: "60v", nombre: "60 m con vallas", viento: true },
    { id: "100v", nombre: "100 m con vallas", viento: true },
    { id: "110v", nombre: "110 m con vallas", viento: true },
    { id: "400v", nombre: "400 m con vallas", viento: false },
    { id: "3000o", nombre: "3000 m con obstáculos", viento: false },
    { id: "4x100", nombre: "Relevo 4x100 m", viento: false },
    { id: "4x400", nombre: "Relevo 4x400 m", viento: false },
    { id: "20km-marcha", nombre: "20 km marcha", viento: false },
    { id: "35km-marcha", nombre: "35 km marcha", viento: false },
  ],
  campo: [
    { id: "largo", nombre: "Salto largo", viento: true },
    { id: "triple", nombre: "Triple salto", viento: true },
    { id: "alto", nombre: "Salto alto", viento: false },
    { id: "garrocha", nombre: "Salto con garrocha", viento: false },
    { id: "bala", nombre: "Lanzamiento de bala", viento: false },
    { id: "disco", nombre: "Lanzamiento de disco", viento: false },
    { id: "jabalina", nombre: "Lanzamiento de jabalina", viento: false },
    { id: "martillo", nombre: "Lanzamiento de martillo", viento: false },
  ],
  pesas: [
    { id: "clean", nombre: "Clean" },
    { id: "snatch", nombre: "Snatch (arranque)" },
    { id: "snatch-tijera", nombre: "Snatch tijera" },
    { id: "jerk", nombre: "Jerk" },
    { id: "jerk-tijera", nombre: "Jerk tijera" },
    { id: "press-banca", nombre: "Press banca" },
    { id: "cuarto-sentadilla", nombre: "1/4 sentadilla" },
    { id: "media-sentadilla", nombre: "1/2 sentadilla" },
    { id: "sentadilla-profunda", nombre: "Sentadilla profunda" },
    { id: "salto-vertical-abalakov", nombre: "Salto vertical (Abalakov)" },
    { id: "squat-jump", nombre: "Squat jump" },
    { id: "salto-largo-pies-juntos", nombre: "Salto largo a pies juntos" },
  ],
};

export function eventosDisponibles(categoria) {
  if (categoria === "pesas") return EVENTOS.pesas;
  return categoria === "pista" ? EVENTOS.pista : EVENTOS.campo;
}
